name: Developer_Branch_CI
on:
  push:
    branches:
      - 'XPNS-*'
jobs:
  check-bats-version:
    runs-on: self-hosted
    steps:
      - name: clone
        uses: actions/checkout@v4
      - name: my output
      - run: bash file.sh
        shell: bash