name: Developer_Branch_CI
on:
  push:
    branches:
      - 'XPNS-*'
jobs:
  check-bats-version:
    runs-on: self-hosted
    steps:
      - run: bash file.sh
        name: lam learning git hub action
        shell: bash